Switch to a new git prompt

diff --git a/bash/git-ps1 b/bash/git-ps1
--- a/bash/git-ps1
+++ b/bash/git-ps1
@@ -1,147 +1,340 @@
 #!/bin/bash
-#
-# From: https://github.com/fgrehm/git-ps1
-#
-# git-ps1 - git-augmented PS1
-#
-# See README for configuration options.
-#
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, either version 3 of the License, or
-#  (at your option) any later version.
-#
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# #
 
-GIT=`which git`
+# Custom version of https://github.com/xtrementl/dev-bash-git-ps1/blob/master/bash_git_ps1.sh
+#
+#-----------------------------------------------------------------------------------------------
+# Developer's Bash-GIT PS1 Integration
+#-----------------------------------------------------------------------------------------------
+#
+# Description:
+#   Provides simple information about git repository for the bash terminal
+#
+#   Erik Johnson (xtrementl)
+#   Created: 07-29-2009
+#   Updated: 03-31-2011
+#
+#   Special thanks to:
+#     reborg
+#
+#   The PS1 will be formatted as follows:
+#       Non-Git repo:
+#       [{host}: {dir}] -->
+#       $
+#
+#       Git repo:
+#       [{host}: {dir}] {branch}({diff upstream counts}){working dir syms} [{time last commit}] -->
+#       $
+#
+# Notes:
+#   The marker ($) will be colored red/green depending on the result of last command's exit code
+#   For Git repos, the working dir symbols are:
+#       + - staged changes
+#       * - unstaged changes
+#       ^ - stashed changes
+#       % - untracked files
+#
+# Installation:
+#   Add the following line to your .bashrc:
+#       source ~/.bash_git_ps1.sh
+#-----------------------------------------------------------------------------------------------
 
-BRANCH=$($GIT symbolic-ref HEAD 2>/dev/null \
-    || $GIT rev-parse HEAD 2>/dev/null | cut -c1-10 \
-)
+# colors
+case "$TERM" in
+    xterm*|rxvt*|screen*)
+        ESC="\033"
+        RED="\[$ESC[01;31m\]"
+        LIGHT_RED="\[$ESC[1;31m\]"
+        GREEN="\[$ESC[01;32m\]"
+        LIGHT_GREEN="\[$ESC[1;32m\]"
+        GREY="\[$ESC[0;37m\]"
+        CYAN="\[$ESC[01;36m\]"
+        YELLOW="\[$ESC[0;33m\]"
+        LIGHT_VIOLET="\[$ESC[1;35m\]"
+        RESET="\[$ESC[0m\]"
+    ;;
+    *)
+        ESC=""
+        RED=""
+        LIGHT_RED=""
+        GREEN=""
+        LIGHT_GREEN=""
+        GREY=""
+        CYAN=""
+        YELLOW=""
+        LIGHT_VIOLET=""
+        RESET=""
+    ;;
+esac
 
-# if no branch or hash was returned, then we're not in a repository
-if [ -z "$BRANCH" ]; then
-    exit
-fi
-
-# creates a color from the given color code
-mkcolor()
-{
-    echo "\[\033[00;$1m\]"
+# prints path to git directory
+__git_dirname() {
+    local dirname
+    if [ -d .git ]; then
+        dirname=".git"
+    else
+        dirname="$(git rev-parse --git-dir 2>/dev/null)"
+    fi
+    echo "$dirname"
 }
 
-BRANCH=${BRANCH#refs/heads/}
-GIT_STATUS=$( $GIT status 2>/dev/null )
+# gets the branching state of the repository
+# optional arg: path to git directory
+__git_branching_state() {
+    local gitdir="$1" || "$(__git_dirname)"
+    local state
 
-# colors can be overridden via the GITPS1_COLOR_* environment variables
-COLOR_DEFAULT=$( mkcolor ${GITPS1_COLOR_DEFAULT:-33} )
-COLOR_FASTFWD=$( mkcolor ${GITPS1_COLOR_FASTFWD:-31} )
-COLOR_STAGED=$( mkcolor ${GITPS1_COLOR_STAGED:-32} )
-COLOR_UNTRACKED=$( mkcolor ${GITPS1_COLOR_UNTRACKED:-31} )
-COLOR_UNSTAGED=$( mkcolor ${GITPS1_COLOR_UNSTAGED:-33} )
-COLOR_AHEAD=$( mkcolor ${GITPS1_COLOR_AHEAD:-33} )
-
-# indicators may be overridden via the GITPS1_IND_* environment vars; set to
-# '0' to disable
-IND_STAGED=${GITPS1_IND_STAGED:-*}
-IND_UNSTAGED=${GITPS1_IND_UNSTAGED:-*}
-IND_UNTRACKED=${GITPS1_IND_UNTRACKED:-*}
-IND_AHEAD=${GITPS1_IND_AHEAD:-@}
-IND_AHEAD_COUNT=${GITPS1_IND_AHEAD_COUNT:-@}
-
-STATUS=''
-COLOR=$COLOR_DEFAULT
-NO_COLOR=$( mkcolor 0 )
-
-# uncommited files
-if [ "$IND_UNSTAGED" != '0' ]; then
-    $GIT diff --no-ext-diff --quiet --exit-code || \
-        STATUS="${STATUS}${COLOR_UNSTAGED}${IND_UNSTAGED}"
-fi
-
-# not on branch/behind origin
-if [ "$( echo $GIT_STATUS | grep 'Not currently on\|is behind' )" ]; then
-    COLOR=$COLOR_FASTFWD
-fi
-
-# staged
-if [  "$IND_STAGED" != '0' ]; then
-    if [ "$( echo $GIT_STATUS | grep 'to be committed' )" ]; then
-        STATUS="${STATUS}${COLOR_STAGED}${IND_STAGED}"
-    fi
-fi
-
-# untracked
-if [ "$IND_UNTRACKED" != '0' ]; then
-    if [ -n "$( $GIT ls-files --others --exclude-standard )" ]; then
-        STATUS="${STATUS}${COLOR_UNTRACKED}${IND_UNTRACKED}"
-    fi
-fi
-
-# ahead of tracking
-if [ "$IND_AHEAD" != '0' ]; then
-    if [ "$( echo $GIT_STATUS | grep 'is ahead' )" ]; then
-        STATUS="${STATUS}${COLOR_AHEAD}${IND_AHEAD}"
-
-        # append count?
-        if [ "$IND_AHEAD_COUNT" != '0' ]; then
-            AHEAD_COUNT=$( echo $GIT_STATUS \
-                | grep -o 'by [0-9]\+ commits\?' \
-                | cut -d' ' -f2 \
-            )
-            STATUS="${STATUS}${AHEAD_COUNT}"
+    if [ -f "$gitdir/rebase-merge/interactive" ]; then
+        state="rebase-i"
+    elif [ -d "$gitdir/rebase-merge" ]; then
+        state="rebase-m"
+    else
+        if [ -d "$gitdir/rebase-apply" ]; then
+            if [ -f "$gitdir/rebase-apply/rebasing" ]; then
+                state="rebase"
+            elif [ -f "$gitdir/rebase-apply/applying" ]; then
+                state="am"
+            else
+                state="am/r"
+            fi
+        elif [ -f "$gitdir/MERGE_HEAD" ]; then
+            state="merge" # merging
+        elif [ -f "$gitdir/BISECT_LOG" ]; then
+            state="bisect" # bisecting
         fi
     fi
-fi
-
-# Since last commit based on https://gist.github.com/926846
-
-function format_unit {
-  local UNIT=$1
-  case "$UNIT" in
-      seconds) UNIT="s" ;;
-      minutes) UNIT="m" ;;
-      hours) UNIT="h" ;;
-      days) UNIT="d" ;;
-      weeks) UNIT="w" ;;
-      months) UNIT="mo" ;;
-      years) UNIT="yr" ;;
-      *);;
-  esac
-  echo ${UNIT}
+    echo "$state"
 }
 
-SINCE_LAST_COMMIT=$($GIT log --pretty=format:'%ar' -1)
-SINCE_LAST_COMMIT=(${SINCE_LAST_COMMIT// / })
+# prints the working directory state of the repository using symbols
+# these could be expensive.. would make sense to have configs to turn off
+# * - modified / + - staged / ^ - stashed / % - untracked
+__git_working_dir_symbols() {
+    local symbols
 
-VALUE=${SINCE_LAST_COMMIT[0]}
+    # in working dir
+    if [ true = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
+        if git rev-parse --quiet --verify HEAD >/dev/null; then
+            added=$(git diff-index --cached HEAD | wc -l)
+            git diff-index --cached --quiet HEAD -- || symbols="${symbols} ${added}+"
+        fi
+        modified=$(git diff --no-ext-diff --name-only | wc -l)
+        git diff --no-ext-diff --quiet --exit-code || symbols="${symbols} ${modified}*"
+    fi
 
-UNIT=$(format_unit ${SINCE_LAST_COMMIT[1]/,/})
+    # stashed
+    if (git rev-parse --verify refs/stash >/dev/null 2>&1); then
+      stashed=$(git stash list 2>&1 | wc -l)
+      (test $stashed -gt 0) && symbols="${symbols} ${stashed}^"
+    fi
 
-# for old projects, git reports years and months
-if [ ${SINCE_LAST_COMMIT[2]} != "ago" ]; then
-  EXTRA_VALUE=${SINCE_LAST_COMMIT[2]}
-  EXTRA_UNIT=$(format_unit ${SINCE_LAST_COMMIT[3]/,/})
-fi
+    # untracked files
+    untracked=$(git ls-files --others --exclude-standard | wc -l)
+    if [ "${untracked}" -gt 0 ]; then
+        symbols="${symbols} ${untracked}%"
+    fi
+    echo "$symbols"
+}
 
-DELTA_COLOR=''
-if [ "$UNIT" == "s" ] || [ "$UNIT" == "m" ]; then
-  DELTA_COLOR=$( mkcolor 32 )
-elif [ "$UNIT" == "h" ]; then
-  DELTA_COLOR=$( mkcolor 33 )
-else
-  DELTA_COLOR=$( mkcolor 31 )
-fi
+# prints current / parent branch name
+# optional arg: 'parent' -- returns a limited guess of the parent
+# optional arg: path to git directory
+__git_branch_name() {
+    # current branch name
+    local branch
+    local gitdir="$2" || "$(__git_dirname)"
+    branch="$(git symbolic-ref HEAD 2>/dev/null)" || {
+        branch="$(git describe --contains --all HEAD 2>/dev/null)" ||
+            branch="$(cut -c1-7 "$gitdir/HEAD" 2>/dev/null)..." ||
+                branch="unknown"
 
-DELTA="${VALUE}${UNIT}${EXTRA_VALUE}${EXTRA_UNIT}"
-DELTA="${NO_COLOR} ∆ ${DELTA_COLOR}${DELTA}${NO_COLOR}"
+        branch="${branch##remotes/}"
+        branch="($branch)"
+    }
+    branch="${branch##refs/heads/}"
 
-# output the status string
-echo "$COLOR[${BRANCH}${STATUS}${COLOR}${DELTA}${COLOR}]$NO_COLOR "
+    # parent branch name
+    if [ parent = "$1" ]; then
+        if [ master = "$branch" ]; then
+            local refs="$(git for-each-ref --format="%(refname:short)")"
+            case "$refs" in
+                *git-svn*) # git-svn repo
+                    branch='git-svn' ;;
+                *origin*) # remote clone
+                    branch='origin' ;;
+                *)
+                    branch='HEAD' ;; # same repo
+            esac
+        else
+            # TODO.. would be nice to improve this to determine the actual
+            # merge base (git merge-base) and compare against that instead of
+            # always assuming master. In this way a 'topic/feature' branch
+            # would show the diff counts for its parent 'next/develop' branch
+            # rather than those plus those on the 'next/develop' branch.
+            # I don't think we want to loop over the refs comparing ... that's
+            # fuzzy.
+            branch='master' # on a branch
+        fi
+    fi
+    echo "$branch"
+}
+
+# prints if inside git directory or bare git repository
+__git_in_gitdir() {
+    if [ true = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]; then
+        if [ true = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]; then
+            echo 'bare'
+        else
+            echo 'gitdir'
+        fi
+    fi
+}
+
+# prints number of commits that are available on ref B but not ref A
+# arg1: reference A
+# arg2: reference B
+__git_commit_diff_count() {
+    echo "$(git rev-list $1..$2 2>/dev/null | awk 'END {print NR}')"
+}
+
+# build combined (+/-) counts for related commits
+__git_count_str() {
+    local str
+    local parent="$(__git_branch_name parent)"
+    local ahead_count="$(__git_commit_diff_count $parent HEAD)"
+    local behind_count="$(__git_commit_diff_count HEAD $parent)"
+
+    if [ 0 -lt "$ahead_count" ]; then
+        str="${GREEN}+${ahead_count}${RESET}"
+    fi
+
+    if [ 0 -lt "$behind_count" ]; then
+        [ -n "$str" ] && str="$str/"
+        str="${str}${RED}-${behind_count}${RESET}"
+    fi
+
+    [ -n "$str" ] && str="($str)"
+    echo "$str"
+}
+
+# get the unix timestamp for the lastest commit (seconds)
+__git_secs_since() {
+    local now="$(date +%s)"
+    local last_commit="$(git log --format='%at' -1 2>/dev/null)"
+    if [ -z "$last_commit" ]; then # probably initial git init, no commits
+        return
+    fi
+    if [ 0 -lt "$now" ] && [ 0 -lt "$last_commit" ]; then
+        echo "$((now - last_commit))"
+    fi
+}
+
+# prints a relative-formatted time string from unix timestamp
+# arg: unix timestamp in seconds
+# optional arg: true to include coloring
+__git_timestr_relformat() {
+    local secs="$1"
+    local yrs="$(( $secs / 31557600 ))"
+    local div="$(( $secs % 31557600 ))"
+    local days="$(( div / 86400 ))"
+    div="$(( $secs % 86400 ))"
+    local hrs="$(( $div / 3600 ))"
+    div="$(( $secs % 3600 ))"
+    local mins="$(( $div / 60 ))"
+
+    # create the formatted time string
+    local timestr
+    [ 0 -lt "$yrs" ] && timestr="${yrs}y"
+    if [ 0 -lt "$days" ]; then
+        [ -n "$timestr" ] && timestr="$timestr,"
+        timestr="${days}d"
+    fi
+    if [ 0 -lt "$hrs" ]; then
+        [ -n "$timestr" ] && timestr="$timestr,"
+        timestr="${timestr}${hrs}h"
+    fi
+    [ -n "$timestr" ] && timestr="${timestr},"
+    timestr="${timestr}${mins}m"
+
+    # add a hint of color
+    if [ -n "$2" ]; then
+        local color
+        if [ 1800 -lt "$secs" ]; then # 30 mins
+            color="$LIGHT_RED"
+        elif [ 600 -lt "$secs" ]; then # 10 mins
+            color="$YELLOW"
+        else
+            color="$LIGHT_GREEN"
+        fi
+        timestr="${color}${timestr}${RESET}"
+    fi
+    echo "$timestr"
+}
+
+# install git integration into PS1
+__git_prompt() {
+    local last_exit="$?" # keep here.. so we get the last command
+
+    # setup PS1
+    local host="${GREY}\h${RESET}"
+    local dir="${GREY}\W${RESET}"
+    PS1="[$host • $dir]"
+
+    # when in git repository
+    local gitdir="$(__git_dirname)"
+    if [ -n "$gitdir" ]; then
+        local branch
+        local extras
+
+        local in_gitdir="$(__git_in_gitdir)"
+        case "$in_gitdir" in
+            gitdir|bare)
+                branch="~$(echo $in_gitdir | tr "[:lower:]" "[:upper:]")~"
+                extras=""
+            ;;
+            *)
+                local branch="$(__git_branch_name current ${gitdir})"
+                local br_state="$(__git_branching_state $gitdir)"
+
+                # rebasing..use merge head for branch name
+                case "$br_state" in
+                    rebase-*)
+                        # get the ref head during rebase
+                        branch="$(cat "$gitdir/rebase-merge/head-name")"
+                        branch="${branch##refs/heads/}"
+                        branch="${branch##remotes/}"
+                    ;;
+                esac
+
+                # extras (count strings, working dir symbols)
+                local countstr="$(__git_count_str)"
+                local wd_syms="${YELLOW}$(__git_working_dir_symbols)${RESET}"
+
+                # calc relative time diff of last commit
+                local secs="$(__git_secs_since)"
+                if [ -n "$secs" ]; then
+                    local timestr=" [$(__git_timestr_relformat $secs true)]"
+                    extras="${countstr}${wd_syms}${timestr}"
+                else
+                    extras="${countstr}${wd_syms}"
+                fi
+            ;;
+        esac
+        branch="${YELLOW}${branch}${RESET}"
+
+        # update PS1
+        PS1="${PS1} ${branch}${extras}\n"
+    else
+        PS1="${PS1} "
+    fi
+
+    # setup marker that acts off of last exit code
+    local marker
+    if [ 0 -eq "$last_exit" ]; then
+        marker="$GREEN"
+    else
+        marker="$RED"
+    fi
+    marker="${marker}\$${RESET}"
+    PS1="${PS1}${marker} "
+}
+PROMPT_COMMAND=__git_prompt
